# Generated by Django 6.0.4 on 2026-05-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='reports/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
